# render.yaml
services:
  - type: web
    name: mcp-chat-interface
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python3 web_chat_interface.py
    envVars:
      - key: PORT
        value: 8080
      - key: PYTHON_VERSION
        value: 3.11.0
    healthCheckPath: /api/health
