# render.yaml
services:
  - type: web
    name: mcp-chat-interface
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: python render_start.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: RENDER
        value: "true"
    healthCheckPath: /api/health
