# render.yaml
services:
  - name: mcp-server
    type: web           # ← use “web”, not “web_service”
    env: python
    region: oregon      # or your chosen region
    plan: free          # or starter/standard
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        value: sqlite:///./ops_center.db
