# render.yaml
services:
  - type: web_service
    name: mcp-server
    env: python
    region: oregon     # or your preferred region
    plan: free         # or starter/standard if you need more CPU/memory
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        value: sqlite:///./ops_center.db
